name: Replay messages from SNS DLQ
on:
  workflow_dispatch:
    inputs:
      dlqQueue:
        description: "Pass the queue you want to move messages from"
        required: true
      destinationQueue:
        description: "Pass the queue you want to move messages to"
        required: true

jobs:
  replay-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: esvm/tcc
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          path: .github/actions/esvm/tcc

      - name: Replay messages in DLQ
        uses: ./.github/actions/esvm/tcc/actions
        with:
          source_queue: ${{ github.event.inputs.dlqQueue }}
          destination_queue: ${{ github.event.inputs.destinationQueue }}
          aws_access_key_id: AKIAYMLVC673FOALQBUM
          aws_secret_access_key: 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
